version: '3.8'

services:
  api:
    build: .
    command: python src/api/server.py
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - redis

  monitor:
    build: .
    command: python src/monitors/monitor.py
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - redis
      - api

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  redis_data:
