services:
  # Main web service
  - type: web
    name: solana-data-collector
    runtime: docker
    region: oregon
    plan: starter
    dockerfilePath: Dockerfile
    dockerContext: .
    branch: main
    autoDeploy: false
    healthCheckPath: /api/health
    numInstances: 1
    envVars:
      - key: PYTHONPATH
        value: /app
      - key: PYTHON_VERSION
        value: "3.10.0"
      - key: LOG_LEVEL
        value: INFO
