services:
  # Main web service
  - type: web
    name: solana-data-collector
    runtime: docker
    region: oregon
    plan: starter
    dockerfilePath: Dockerfile
    dockerContext: .
    branch: main
    autoDeploy: false
    healthCheckPath: /
    numInstances: 1
    startCommand: python -m src.main
    envVars:
      - key: PYTHONPATH
        value: /app
      - key: PYTHON_VERSION
        value: "3.10.0"
      - key: LOG_LEVEL
        value: INFO
      - key: RENDER
        value: "1"
      - key: PORT
        value: "10000"
      - key: PGUSER
        sync: false
      - key: PGPASSWORD
        sync: false
      - key: PGHOST
        sync: false
      - key: PGPORT
        value: "6543"  # Render's connection pooler port
      - key: PGDATABASE
        sync: false
      - key: PGSSLMODE
        value: "require"
      - key: CONNECT_TIMEOUT
        value: "30"
      - key: SQLALCHEMY_POOL_SIZE
        value: "5"  # Updated to match .env
      - key: SQLALCHEMY_MAX_OVERFLOW
        value: "10"
      - key: SQLALCHEMY_POOL_TIMEOUT
        value: "30"
      - key: SQLALCHEMY_POOL_RECYCLE
        value: "1800"
      - key: USE_MOCK_DATA
        value: "true"  # Added from .env
      - key: TEST_MODE
        value: "true"  # Added from .env
