services:
  # Main web service
  - type: web
    name: solana-data-collector
    env: python
    region: oregon
    plan: starter
    runtime: python3.11
    buildCommand: |
      # Update package lists and install system dependencies
      apt-get -y update
      apt-get -y upgrade
      apt-get install -y --no-install-recommends \
        build-essential \
        libffi-dev \
        python3-dev \
        pkg-config \
        libssl-dev \
        python3.11-dev \
        gcc \
        g++ \
        make
      
      # Clean up apt cache
      apt-get clean
      rm -rf /var/lib/apt/lists/*
      
      # Upgrade pip and install build tools
      python -m pip install --no-cache-dir --upgrade pip setuptools wheel
      
      # Install cryptography with explicit version and build dependencies
      pip install --no-cache-dir cryptography==41.0.7
      
      # Install other requirements
      pip install --no-cache-dir -r requirements.txt
      
      # Verify deployment
      python scripts/deploy_verify.py
    startCommand: uvicorn src.api.dashboard:app --host 0.0.0.0 --port $PORT
    autoDeploy: false
    healthCheckPath: /api/health
    numInstances: 1
    envVars:
      - key: PYTHONPATH
        value: /app
      - key: PYTHON_VERSION
        value: 3.11.3
      - key: LOG_LEVEL
        value: INFO
      - key: MONITORING_INTERVAL
        value: 10
      - key: MAX_CONCURRENT_TASKS
        value: 5
      - key: PORT
        value: 8000
      # Secure environment variables
      - key: DATABASE_URL
        sync: false
      - key: HELIUS_API_KEY
        sync: false
      - key: TWITTER_API_KEY
        sync: false
      - key: DISCORD_WEBHOOK_URL
        sync: false
      - key: SOLSCAN_API_KEY
        sync: false
      - key: SHYFT_API_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
    disk:
      name: data
      mountPath: /data
      sizeGB: 10
    scaling:
      minInstances: 1
      maxInstances: 3
      targetMemoryPercent: 80
    metrics:
      - type: cpu
      - type: memory
      - type: requests
    alerts:
      - type: cpu
        threshold: 80
        window: 5m
      - type: memory
        threshold: 80
        window: 5m
      - type: http_error_rate
        threshold: 5
        window: 5m
