services:
  # Main web service
  - type: web
    name: solana-data-collector
    runtime: docker
    region: oregon
    plan: starter
    dockerfilePath: Dockerfile
    dockerContext: .
    branch: deployment/2025-01-14
    autoDeploy: false
    healthCheckPath: /api/health
    numInstances: 1
    envVars:
      - key: PYTHONPATH
        value: /app
      - key: PYTHON_VERSION
        value: "3.11.3"
      - key: LOG_LEVEL
        value: INFO
