"""Initial migration

Revision ID: b820f2f6b72e
Revises: 
Create Date: 2025-01-14 15:45:48.819685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b820f2f6b72e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metric_type', sa.String(length=50), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_metric_time', 'system_metrics', ['metric_type', 'timestamp'], unique=False)
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=44), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('decimals', sa.Integer(), nullable=True),
    sa.Column('total_supply', sa.Float(), nullable=True),
    sa.Column('holder_count', sa.Integer(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('token_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address')
    )
    op.create_index('idx_token_address', 'tokens', ['address'], unique=False)
    op.create_index('idx_token_holder_count', 'tokens', ['holder_count'], unique=False)
    op.create_index('idx_token_symbol', 'tokens', ['symbol'], unique=False)
    op.create_table('wallet_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_address', sa.String(length=44), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('total_value_usd', sa.Float(), nullable=True),
    sa.Column('transaction_count', sa.Integer(), nullable=True),
    sa.Column('first_transaction', sa.DateTime(), nullable=True),
    sa.Column('last_transaction', sa.DateTime(), nullable=True),
    sa.Column('analysis_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_wallet_address', 'wallet_analyses', ['wallet_address'], unique=False)
    op.create_index('idx_wallet_value', 'wallet_analyses', ['total_value_usd'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=True),
    sa.Column('alert_type', sa.String(length=50), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notification_channels', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_triggered', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alert_token', 'alerts', ['token_id'], unique=False)
    op.create_index('idx_alert_type', 'alerts', ['alert_type'], unique=False)
    op.create_table('token_holders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('wallet_address', sa.String(length=44), nullable=False),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_holder_balance', 'token_holders', ['token_id', 'balance'], unique=False)
    op.create_index('idx_holder_token', 'token_holders', ['token_id', 'wallet_address'], unique=False)
    op.create_table('token_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('price_usd', sa.Float(), nullable=True),
    sa.Column('volume_24h', sa.Float(), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_price_timestamp', 'token_prices', ['timestamp'], unique=False)
    op.create_index('idx_token_price_time', 'token_prices', ['token_id', 'timestamp'], unique=False)
    op.create_table('token_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('transaction_hash', sa.String(length=88), nullable=False),
    sa.Column('from_address', sa.String(length=44), nullable=True),
    sa.Column('to_address', sa.String(length=44), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tx_addresses', 'token_transactions', ['from_address', 'to_address'], unique=False)
    op.create_index('idx_tx_token_time', 'token_transactions', ['token_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tx_token_time', table_name='token_transactions')
    op.drop_index('idx_tx_addresses', table_name='token_transactions')
    op.drop_table('token_transactions')
    op.drop_index('idx_token_price_time', table_name='token_prices')
    op.drop_index('idx_price_timestamp', table_name='token_prices')
    op.drop_table('token_prices')
    op.drop_index('idx_holder_token', table_name='token_holders')
    op.drop_index('idx_holder_balance', table_name='token_holders')
    op.drop_table('token_holders')
    op.drop_index('idx_alert_type', table_name='alerts')
    op.drop_index('idx_alert_token', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('idx_wallet_value', table_name='wallet_analyses')
    op.drop_index('idx_wallet_address', table_name='wallet_analyses')
    op.drop_table('wallet_analyses')
    op.drop_index('idx_token_symbol', table_name='tokens')
    op.drop_index('idx_token_holder_count', table_name='tokens')
    op.drop_index('idx_token_address', table_name='tokens')
    op.drop_table('tokens')
    op.drop_index('idx_metric_time', table_name='system_metrics')
    op.drop_table('system_metrics')
    # ### end Alembic commands ###
